config/routes.rb
Rails.application.routes.draw do


  root "proposals#index"

  resources :proposals, except: :delete do
    resources :experiments, except: [:delete, :index] do
      resources :observations, only: [:new, :create, :show]
      resources :procedures, only: [:show, :new, :create] do
        resources :observations, only: [:new, :create, :show]
      end
    end
  end

  resources :users, only: [:new, :create]

  get '/users/login' => "users#login"
  post '/users/login' => "users#loggingin"
  get '/users/logout' => "users#logout"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  belongs_to :proposal

  has_many :observations, as: :observable

  has_many :procedures

  validates :name, :description, presence: true
end

app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to :observable, polymorphic: true
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :experiment
  has_many :observations, as: :observable

  validates :title, :steps, :experiment_id, presence: true

end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :requestor, class_name: :User
  has_one :experimentor, class_name: :User
  has_many :users
  has_one :experiment

  validates :summary, :hypothesis, :title, presence: true

  def experimentor
    User.find_by_id(experimentor_id)
  end

  def experimentor=(experimentor)
    experimentor_id = experimentor.id
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :proposals, class_name: "Proposal", foreign_key: :requestor_id
  has_many :experiments, through: :proposals, foreign_key: :experimentor_id
  has_secure_password

  validates :username, :password, {:presence => true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def experimentor?(proposal)
    current_user == proposal.experimentor
  end

  helper_method :current_user
  helper_method :logged_in?
  helper_method :experimentor?

end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController

  before_action :set_proposal
  before_action :set_experiment, except: [:create, :new]

  def show
  end

  def new
    @experiment = Experiment.new
    redirect_to proposal_path(@proposal) unless logged_in? && !@proposal.experiment
  end

  def edit
    redirect_to proposal_experiment_path(@experiment.proposal, @experiment) unless experimentor?(@proposal)
  end

  def create
    @experiment = Experiment.new(experiment_params)
    if logged_in? && !@proposal.experiment
      @proposal.assign_attributes(experimentor_id: current_user.id)
      @experiment.proposal = @proposal
      if @experiment.save
        @proposal.status = "in progress"
        @proposal.save
        redirect_to @proposal
      else
        @errors = @experiment.errors.full_messages
        render :new
      end
    else
      redirect_to proposal_path(@proposal)
    end
  end

  def update
    if experimentor?(@proposal)
      if @experiment.update(experiment_params)
        @proposal.update_attributes(status: "closed") if @experiment.results != "" || @experiment.conclusion != ""
        redirect_to proposal_experiment_path(@experiment.proposal, @experiment)
      else
        @errors = @experiment.errors.full_messages
        render :edit
      end
    else
      redirect_to proposal_experiment_path(@experiment.proposal, @experiment)
    end
  end

  private

  def set_proposal
    @proposal = Proposal.find(params[:proposal_id])
  end

  def set_experiment
    @experiment = Experiment.find(params[:id])
  end

  def experiment_params
    params.require(:experiment).permit(:name, :description, :results, :conclusion)
  end
end

app/controllers/observations_controller.rb
class ObservationsController < ApplicationController
  before_action :set_experiment, only: [:new, :create, :show]

  def new
    @observation = Observation.new
    @proposal = Proposal.find(params[:proposal_id])
    @experiment = Experiment.find(params[:experiment_id])
    if request.path_info.include?("procedures")

      @procedure = Procedure.find(params[:procedure_id])
      @form_params = [@proposal, @experiment,@procedure,@observation]
    else
      @form_params = [@proposal, @experiment, @observation]
    end

    render 'observations/new'
  end

  def create
    @observation = Observation.new(observation_params)

    if @observation.save

      if request.path_info.include?("procedures")
        redirect_to "/proposals/#{params[:proposal_id]}/experiments/#{params[:experiment_id]}/procedures"
        # correct_path = response.request_path.split('/')
        # correct_path.delete(-1)
        # correct_path.join("/")
        # redirect_to correct_path
      else
         redirect_to "/proposals/#{params[:proposal_id]}/experiments/#{params[:experiment_id]}"
      end
    else
        render 'observations/new'
    end
  end


  def show
  end

  private

  def set_experiment
    @experiment = Experiment.find(params[:experiment_id])
  end

  def observation_params
    params.require(:observation).permit(:body, :observable_type, :observable_id)
  end
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :set_experiment, only: [:show, :create]
  before_action :set_procedure, only: [:show]
  before_action :set_proposal, only: [:show]

  def show
  end

  def new
    @procedure = Procedure.new
  end

  def create
    @procedure = Procedure.new(procedure_params)
    @procedure.experiment = @experiment

    if @procedure.save
      redirect_to proposal_experiment_path(@experiment.proposal, @experiment)
    else
      @errors = @procedure.errors.full_messages
      render :new
    end
  end

  private
    def procedure_params
      params.require(:procedure).permit(:title, :steps, :experiment)
    end

    def set_proposal
      @proposal = Proposal.find(params[:proposal_id])
    end

    def set_experiment
      @experiment = Experiment.find(params[:experiment_id])
    end

    def set_procedure
      @procedure = Procedure.find(params[:id])
    end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  def index
      @proposals = Proposal.all
    end

    def show
      @proposal = Proposal.find(params[:id])
    end

    def new
      @proposal = Proposal.new
      redirect_to proposals_path unless logged_in?
    end

    def create
      @proposal = Proposal.new(proposal_params)
      if logged_in?
        @proposal.requestor = current_user
        @proposal.status = "open"
        if @proposal.save
          redirect_to @proposal
        else
          @errors = @proposal.errors.full_messages
          render :new
        end
      else
        redirect_to proposals_path
      end
    end

    def edit
      @proposal = Proposal.find(params[:id])
    end

    def update
      @proposal = Proposal.find(params[:id])

      if @proposal.update(proposal_params)
        redirect_to @proposal
      else
        render 'edit'
      end
    end

    private
      def proposal_params
         params.require(:proposal).permit(:summary, :hypothesis, :status, :title)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create

    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  def login
    @user = User.new
  end

  def loggingin
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id]= @user.id
      redirect_to '/'
    else
      @errors = ["Username/Password invalid."]
      @user = User.new
      render :login
    end
  end

  def logout
    session.clear
    redirect_to '/'
  end

  private
    def user_params
      params[:user][:role] = params[:role]
      params.require(:user).permit(:username, :password, :role)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/observation_helper.rb
module ObservationHelper
end

app/helpers/users_helper.rb
module UsersHelper

  
end

app/views/experiments/_form.html.erb
<%= form_for [@proposal, @experiment] do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :description %>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.label :results %>
  <%= f.text_area :results %>
</p>

<p>
  <%= f.label :conclusion %>
  <%= f.text_area :conclusion %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/experiments/edit.html.erb
<h1> Update Experiment </h1>
<%= render :partial => './errors' %>
<%= render 'form' %>

<%= link_to "Back", proposal_experiment_path(@experiment.proposal, @experiment) %>

app/views/experiments/new.html.erb
<h1>New Experiment</h1>
<%= render :partial => './errors' %>
<%= render 'form' %>

<%= link_to "Back", proposal_path(@proposal) %>

app/views/experiments/show.html.erb
<h1> <%= @experiment.name %> </h1>

<h2>Description</h2>
<p>
  <%= @experiment.description %>
</p>

<% if @experiment.results != "" %>
<h2>Results</h2>
<p>
  <%= @experiment.results %>
</p>
<%end%>

<% if @experiment.conclusion != "" %>
  <h2>Conclusion</h2>
  <p>
    <%= @experiment.conclusion %>
  </p>
<%end%>

<% if experimentor?(@proposal) %>
<%=link_to "Edit", edit_proposal_experiment_path(@experiment.proposal, @experiment)%>
<% end %>

<%=link_to "Back", proposal_path(@experiment.proposal)%>


<% if @experiment.procedures %>
  <div class="">
      <ul>
      <% @experiment.procedures.each do |procedure| %>
      <li> <%= link_to procedure.title, proposal_experiment_procedure_path(@proposal, @experiment, procedure) %></li>
    <%end %>
      </ul>
  </div>
<% end %>

<%= link_to "Add Procedure", new_proposal_experiment_procedure_path(@experiment.proposal, @experiment)  %>

<%= link_to 'Create Observation', new_proposal_experiment_observation_path(@experiment.proposal, @experiment) %>

<% if @experiment.observations.any? %>
  <p>Observations </p>
  <ul>
  <% @experiment.observations.each do |observation| %>

    <li><%= observation.body %></li>
    <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookiesAndCream</title>
    <link href="https://fonts.googleapis.com/css?family=Bubbler+One|Open+Sans" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <div id="header">
        <div class="header-logo">
          <a href="/"><h1>Cookies&amp;Cream</h1></a>
        </div>
        <div class="header-nav">
          <%= link_to "Home", proposals_path%>
          <span>•</span>
          <% if logged_in? %>
            <%= link_to "Log out!", users_logout_path%>
          <%else%>
            <%= link_to "Register!", new_user_path%>
            <span>•</span>
            <%= link_to "Log in!", users_login_path%>
          <%end%>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/observations/new.html.erb
<div class="form-section">
  <div class="form-wrapper">

<h2>Create an Observation</h2>

<%= form_for @form_params do |f| %>
<p>
  <%= f.label :body %>
  <%= f.text_field :body, class: 'form-textfield' %>
</p>

<p>
<%= f.hidden_field :observable_id, :value => @experiment.id %>
</p>

<p>
<%= f.hidden_field :observable_type, :value => "Experiment" %>
</p>

<p>
  <%= f.submit class: 'submit-button' %>
</p>

<% end %>
</div>
</div>

app/views/observations/new_e.html.erb
<h1>Create an Observation</h1>

<%= form_for [@experiment, @observation] do |f| %>
<p>
  <%= f.label :body %>
  <%= f.text_field :body %>
</p>

<p>
<%= f.hidden_field :observable_id, :value => @experiment.id %>
</p>

<p>
<%= f.hidden_field :observable_type, :value => "Experiment" %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/procedures/edit.html.erb
Show the form to edit

app/views/procedures/new.html.erb
<h1>New Procedure</h1>

<%= render :partial => './errors' %>

<%= form_for @procedure, url: {action: "create"} do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :steps %> <br>
  <%= f.text_area :steps %>
  <%= f.submit%>

<% end %>

app/views/procedures/show.html.erb
<div class="">
  <h1> <%= @procedure.title %></h1>
</div>

<div class="">
    <p><%= @procedure.steps %></p>
</div>

<div class="proposal-link">
  <%= link_to 'Create Observation', new_proposal_experiment_procedure_observation_path(@procedure.experiment.proposal, @procedure.experiment, @procedure) %>
</div>
<% if @procedure.observations.any? %>
  <p>Observations </p>
  <ul>
  <% @procedure.observations.each do |observation| %>

    <li><%= observation.body %></li>
    <% end %>
</ul>
<% end %>

app/views/proposals/edit.html.erb
<h1> Edit Proposal</h1>
<%= render :partial => './errors' %>

<%= form_for([@proposal]) do |f|%>
  <% if @proposal.errors.any? %>
  <h4>
    <%= pluralize(@proposal.errors.count, "error") %>
    prohibited this proposal from being saved:
  </h4>
  <ul>
    <% @proposal.errors.full_messages.each do |msg| %>
    <li> <%= msg %></li>
    <% end %>
  </ul>

<% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %> <br>
    <%= f.label :summary %>
    <%= f.text_area :summary %> <br>
    <%= f.label :hypothesis %>
    <%= f.text_area :hypothesis%> <br>

    <%= f.submit %>
  </p>

<% end %>

app/views/proposals/index.html.erb
<h1> Proposals</h1>

<ul>
<% @proposals.each do |proposal| %>
  <li> <%= link_to  proposal.title, proposal %></li>
<% end %>
</ul>

<% if logged_in? && current_user.role == "Faculty" %>
	<div class="proposal-link">
		<%= link_to 'Create new proposal', new_proposal_path %>
	</div>
<% end %>

app/views/proposals/new.html.erb
<div class="form-section">
  <div class="form-wrapper">
    <h2>Create A New Proposal</h2>
    <%= form_for([@proposal]) do |f|%>
      <%= render :partial => './errors' %>

      <p>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-textfield' %> <br>
        <%= f.label :summary %>
        <%= f.text_area :summary, class: 'form-textfield' %> <br>
        <%= f.label :hypothesis %>
        <%= f.text_area :hypothesis, class: 'form-textfield'%> <br>
      </p>
      <%= f.submit "Create New Proposal", class: 'submit-button' %>
    <% end %>
  </div>
</div>

app/views/proposals/show.html.erb
<h1> <%= @proposal.title %> </h1>

<ul>
  <li>
    Request made by: <%= @proposal.requestor.username %>
  </li>
  <li>
    Summary: <%= @proposal.summary %>
  </li>
  <li>
    Hypothesis: <%= @proposal.hypothesis %>
  </li>
  <li>
    Status: <%= @proposal.status %>
  </li>


  <% if @proposal.status != "open" && @proposal.experimentor %>
  <li>
    Experimentor: <%= @proposal.experimentor.username %>
  </li>

  <% end %>

  <% if @proposal.experiment %>
    <li>
      <%= link_to "Experiment", proposal_experiment_path(@proposal, @proposal.experiment) %>
    </li>
  <% elsif @proposal.status == "open" && current_user.role == "Staff"  %>
    <li>
      <%= link_to "Create experiment", new_proposal_experiment_path(@proposal) %>
    </li>
  <% end %>

</ul>

app/views/users/login.html.erb
<div class="form-section">
  <div class="form-wrapper">
    <h2>Login Form</h2>
    <%= render :partial => './errors' %>
    <%= form_for @user, url: '/users/login'  do |f| %>
    <p>
      <%= f.label :username  %> </br>
      <%= f.text_field :username, class: 'form-textfield' %>
    </p>
    <p>
      <%= f.label :password, "Password" %></br>
      <%= f.password_field :password, class: 'form-textfield' %>
    </p>
    <p>
      <%= f.submit "Log in!", class: 'submit-button'%>
    </p>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="form-section">
  <div class="form-wrapper">
    <h2>Registration Form</h2>
    <%= render :partial => './errors' %>
    <%= form_for @user do |f| %>
    <p>
      <%= f.label :username  %> </br>
      <%= f.text_field :username, class: 'form-textfield' %>
    </p>
    <p>
      <%= f.label :password, "Password" %></br>
      <%= f.password_field :password, class: 'form-textfield' %>
    </p>
    <p>
      <%= f.label :role %> </br>
      <%= select_tag(:role, options_for_select([['Faculty'], ['Staff']])) %>
    </p>
    <p>
      <%= f.submit "Register!", class: 'submit-button'%>
    </p>
    <% end %>
  </div>
</div>